### ISSUE TITLE
rblchk.tcl returns "NULL 0" when there is no TXT record provided by a DNSBL

### ISSUE THREAD

**Issue by Robby-** [aaronhurt/tcl-scripts#1]
rblchk.tcl will not return a positive result eventhough an IP is listed when using DNSBLs that do not provide a TXT record, such as rbl.efnetrbl.org which only provides an A record, and thus allows malicious clients to go unnoticed.

**Comment by aaronhurt** [comment]
Thank you for the report.  I will check this out and provide a fix 
shortly.  Glad to know someone still finds these old things useful.

-- Aaron

**Comment by aaronhurt** [comment]
Fixed:

Previous behavior:

% ::rblchk::score 66.230.230.230
66.230.230.230 NULL 0

New behavior:

% ::rblchk::score 66.230.230.230
66.230.230.230 {{+3.0 rbl.efnetrbl.org {Undesirable clients} {}}} 3.0

**Comment by Robby-** [comment]
No problem, thanks for the fast fix! :)
And yes, quite useful even, I use it to flag suspicious connecting clients on our server.
